sonar.projectKey=PMS
sonar.sources=.
sonar.host.url=http://localhost:9000

# CSS DIPINDAHKAN KE SINI AGAR TIDAK DI-SCAN SAMA SEKALI
sonar.exclusions=**/node_modules/**, **/*.config.js, **/*.json, **/*.sql, frontend/public/**, .vscode/**, .vite/**, backend/coverage/**, **/*.md, .gitignore
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*